### ISSUE TITLE
Create default thumbnail for results with no default preview image

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/chrome-extension#1]

**Comment by chseifert** [comment]
The images are included already :) However, we found, that we need an additional one encoding "other" and/or "unknown". Would suggest a questionmark as symbol.

**Comment by LadyBytes** [comment]
Here you go: 
https://www.dropbox.com/sh/zdzjk1ney7vwen7/AADwvopubsFRjQdbhI0AMvvoa?dl=0

I also corrected a coloring error in the image thumbnail. The inner grey circle is now the same color as the background.

**Comment by chseifert** [comment]
Thx, perfekt!
