### ISSUE TITLE
Position of the search bar's content pane is not properly preserved

### ISSUE THREAD

**Issue by schloett** [EEXCESS/chrome-extension#11]
If you scroll down on a page (e.g. English Wikipedia Main Page) and drag the pane afterwards, it will not show up anymore after reloading that page (because it is positioned somewhere on an area not in the viewport)

**Comment by LadyBytes** [comment]
Exchanging offset() for position() fixed the behaviour for me. But I don't want to close the issue until I'm sure it fixed it for you as well and I'm not overlooking something.

**Comment by schloett** [comment]
works fine for me, position seems to be preserved. However the size seems to be set to a fixed value (at least it does not preserve the previous size)

**Comment by LadyBytes** [comment]
Turns out my if-clauses weren't sufficient. Style additions made whenever a new size was detected were overridden by the following dragging style changes.
