### ISSUE TITLE
Thumbnail media images should have transparent background

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/chrome-extension#24]
copy of https://github.com/EEXCESS/recommender/issues/20#event-417007968
(access rights for assignments in repos different)

**Comment by chseifert** [comment]
Is there any update on this issue?

**Comment by LadyBytes** [comment]
There is an update but it seems the push wasn't recognized by github, I will look into it.
But it seems that I misread the assignment. Do you want me to use transparent coloring for the different records or should I design new default media type symbols with transparent grey background?

**Comment by chseifert** [comment]
The latter, new media types, and instead of the gray background a transparent background. I would need then the images directly to send them to the recommender guy. They are stored somewhere on the server.

**Comment by LadyBytes** [comment]
I see, I will send them to you as soon as I am in front of my laptop!

**Comment by chseifert** [comment]
Thanks, and sorry to not have been clearer before.

**Comment by chseifert** [comment]
Thx, added the download link to issue https://github.com/EEXCESS/recommender/issues/20
