### ISSUE TITLE
Design improvements 

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/chrome-extension#25]
Search result list: 
Use a different color palette for the different media types 
from http://colorbrewer2.org
# fbb4ae
# b3cde3
# ccebc5
# decbe4
# fed9a6

font color: black

**Comment by chseifert** [comment]
Related to https://github.com/EEXCESS/chrome-extension/issues/4

**Comment by mgrani** [comment]
see the screenshot:
![color](https://cloud.githubusercontent.com/assets/1941683/10049585/73c5944e-6218-11e5-8c19-4c24d5e3eaba.png)

**Comment by schloett** [comment]
not sure when the colours actually changed, but the mentioned colour palette is at least present in commit https://github.com/EEXCESS/visualization-widgets/commit/231a3762b32e0117fee8b8dabc0acf47fe69c754
