### ISSUE TITLE
Design Improvement Bar

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/chrome-extension#26]
I would suggest to make the default background color grey, with black text. That is neutral and more independent of the side. A 3d box around the bar would be great. 

<img width="1276" alt="bar" src="https://cloud.githubusercontent.com/assets/1941683/10049725/07bb189a-6219-11e5-9399-2e075e911314.png">

Settings i used here:

> -webkit-font-smoothing: antialiased;
> background-color: rgba(249, 249, 249, 0.980392);
> box-shadow: rgba(0, 0, 0, 0.258824) 0px 2px 5px 0px;
>         box-sizing: border-box;
>         color: rgb(51, 51, 51);
>         display: block;
>         font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;

**Comment by schloett** [comment]
Default color has been changed to some light grey, shadow has been added. We received suggestions for further improvements from designers and are currently integrating them.
