### ISSUE TITLE
Different color for active paragraph

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/chrome-extension#27]
Use a different color, which R-G colourblind people don't perceive as grey, e.g. #2c7fb8 (something blueish)

**Comment by schloett** [comment]
not sure about that, just tried it with a grey colour and the active paragraph is still recognizeable (harder, but recognizeable). Also tried the blue colour and for example on Wikipedia, it seems less obvious, that the paragraph has been marked active by EEXCESS. 
So from my point of view, the green border is the nicer version (score 3) for non colour-blind people and suboptimal, but still working for colour-blind (score 1). The blue border is a compromise for both (score 2). Hence I would vote for score 3 for the majority? (not sure how many people are actually colourblind)
P.S.: substitute "colourblind" by "red-green colourblind" in my comment.

**Comment by schloett** [comment]
will stay as is
