### ISSUE TITLE
[Discussion] Privacy in the chrome extension

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/chrome-extension#28]
Got an comment from a user asking why on installation of the extension the following information are accessed 

A) access and modification to all the browser history
B) access and modification to all data on website that you browse
C) access to geographical position

Could we please collect and reassess which is necessary and why.

My guesses so far
A) for getting good keywords in case the external service is down
B) for highlighting the current paragraph (modify the DOM tree)
C) we don't need this, an artifact?

**Comment by schloett** [comment]
A) not used at the moment, will be removed upon next deployment
B) yes, not only for highlighting, but already for getting access to the page content (finding the paragraphs, ...) and also being able to add the bar at the bottom
C) not needed anymore, will be removed upon next deployment

**Comment by schloett** [comment]
removed the unnecessary right requests in the dev version, according to #30, requestion B) seems to be fine. Will be available in the stable version upon next major release.
