### ISSUE TITLE
Add a possibility to turn off the extension

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/chrome-extension#29]
(comments in the hangout)
- for instance if you want to print a page all the excess stuff will be printed as well
- or if you definitely don't want to have the extension active

Suggestions: simple add the excess button on top (icon), only functionality : TURN ON/OFF

**Comment by schloett** [comment]
integrated turn on/off in the branch [feature/blacklisting](https://github.com/EEXCESS/chrome-extension/tree/featuer/blacklisting) and will find its way into the next major release.
