### ISSUE TITLE
Add explanation for query terms

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/chrome-extension#31]
I received a question as to why MIT is always extracted as a query term (see screenshot, seems to be a German page). I guess this is because the user is on a german page and the disambiguation service finds "mit". We could answer/resolve such questions if we highlight the source for the extracted keyword (on mouse over). 

![image001](https://cloud.githubusercontent.com/assets/4638470/10428173/e6d9fbce-70ef-11e5-8265-e504aaf5d5d4.png)

Issue related to https://github.com/EEXCESS/eexcess/issues/9 where this issue also has been raised.

**Comment by chseifert** [comment]
Just as a note - this "enhancement" is important for the test data collection experiment.

**Comment by schloett** [comment]
highlighting on mouseover integrated in commit https://github.com/EEXCESS/chrome-extension/commit/bd5199f3cdabf3c6fae8619729c27044cd921dab

**Comment by chseifert** [comment]
Keyword hightlighting does not seem to work in all cases
- e.g., no hightlighting for any of the words for page
  http://www.telegraph.co.uk/technology/11285007/Ada-Lovelace-paved-the-way-for-Alan-Turings-more-celebrated-codebreaking-a-century-before-he-was-born.html
  (screenshot 1)
- no highlighting for some words on wikipedia page (see second screenshot)

![extension-keyword-highlighting](https://cloud.githubusercontent.com/assets/4638470/11179352/092c1fd0-8c53-11e5-9e08-c7d1ef5f1b38.png)
![extension-keyword-highlighting2](https://cloud.githubusercontent.com/assets/4638470/11179417/5d75e684-8c53-11e5-9415-55288e6eeaf1.png)

**Comment by schloett** [comment]
first bug fixed in https://github.com/EEXCESS/chrome-extension/commit/34bf67c2aeb38f26c6ccb6d68cb80ca63986300d
second bug fixed in https://github.com/EEXCESS/c4/commit/eca5bc5b6f564cc46f193d264dbb036cf241a970
Updated version of extension (1.3.1) is currently under deployment, should be available within 60minutes.
