### ISSUE TITLE
Add Black and Whitelisting to the Extension

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/chrome-extension#32]
The extension now works on every site, inlcuding my banking website. We need a black/whitelisting mechanism that allows for blocking sites from being analysed by the extension.

**Comment by schloett** [comment]
integrated black-/whitelisting in the branch [feature/blacklisting](https://github.com/EEXCESS/chrome-extension/tree/featuer/blacklisting) and will find its way into the next major release.
