### ISSUE TITLE
Check whether vis components could be loaded on the fly

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/chrome-extension#34]
Up-to date modules available on 
https://eexcess.github.io/visualization-widgets/Dashboard/

(Moodle Plugin fetches this on the fly) - bug fixes could be efficiently integrated. 

Would this work for the Chrome Extension as well?

**Comment by schloett** [comment]
Yes, it does. Moved to the online version for the Dashboard in development-branch. I am not sure, if we should do this for all vis components. In principle, I like the idea, but it also bears two potential risks:
1) github.io may be down (unlikely to happen)
2) erroneous code may be accidentally pushed to the master branch and this would be immediately reflected, since we work on the live system.

**Comment by chseifert** [comment]
I am not sure myself, basically it will make the life for developers easier - but shifts the integration testing to end users. Developer friendly, but not end user friendly - unless the developers of such components thoroughly test. And this could not be expected, if there are dependencies in the integrating components (vis developers will not test the vis in the master version of the chrome extension, and the vis in the moodle plugin, and ...). Just because it would be technically possible, doesn't mean we have to do it ;-)

**Comment by schloett** [comment]
Ok, then for the deployment, I would only include the online version of the Dashboard and include the rest in the extension code. The SearchResultList will be the first visualization, which a user faces and hence I would prefer a local version, which avoids the two problems mentioned before. The FacetScape will probably not be subject to many changes in the future and hence the local version fits better imho as well. Maybe we might add additional widgets as online version in the future, but that could be decided when applicable.
Concusion: yes, loading vis components on the fly is possible.
