### ISSUE TITLE
provide ability for feedback

### ISSUE THREAD

**Issue by schloett** [EEXCESS/chrome-extension#44]
In the GDOCS addon, it is realized via a feedback channel through the webstore. Maybe something similar can be done in the extension.

**Comment by schloett** [comment]
Could not find a possibility to use the webstore as feedback channel. Provided a mailto: link.

**Comment by chseifert** [comment]
![image001](https://cloud.githubusercontent.com/assets/4638470/11035717/6949d718-86f4-11e5-8eed-d7fdf2a1eaa9.jpg)

FIY: There is a possibilty somehow - the vis dashboard uses it. (And as the window on top left shows, it goes through the webstore). Issue can be closed again when you just read it, no need for action imho.

**Comment by chseifert** [comment]
Add-on: whether this way works is discussed in https://github.com/EEXCESS/visualization-widgets/issues/37

**Comment by schloett** [comment]
The window on top left is just a JavaScript alert (c.f. https://jsfiddle.net/Lqnsct9x/). The feedback you received is not in the webstore and I also could not find it in the mailbox associated with the webstore-account. 
![feedback](https://cloud.githubusercontent.com/assets/4618499/11037064/3357c9f0-86fc-11e5-88e2-c82cd279573a.PNG)
However, the URL of the feedback form in the webstore looks stable (https://chrome.google.com/webstore/detail/eexcess/mnicfonfoiffhekefgjlaihcpnbchdbc/support), so I will use this one instead of the mailto link (and hope that it does not change). Leaving this issue open until it is included in the deployed version

**Comment by chseifert** [comment]
Yes, sorry for adding more confusion. Gerwald just noted in https://github.com/EEXCESS/visualization-widgets/issues/37 that the feedback from the vis dashboard is actually sent via the eexcess logging functionality (and thus will only  be read if one has a look at the log files)

**Comment by mgrani** [comment]
hmm, coudl we somehow trigger an e-mail with the feedback? Reading through the logs is highly unlikely to happen.

**Comment by schloett** [comment]
We're talking about two different things:
1) Feedback especially for the Dashboard (see https://github.com/EEXCESS/visualization-widgets/issues/37)
2) Feedback for the Extension (in general)
The feedback for the Dashboard is stored in the logs, I do not know, if they have a notification trigger or plan to evaluate the logs on a periodical basis.
The feedback link in the extension is currently a mailto link, but will link to the feedback form in the webstore in the future (the feedback form is provided by Google and already available when you visit the extension in the store). Unfortunately, there does not seem to be a mail notification upon provision of feedback, but it is displayed in the webstore, so we should check periodically. Apart from that, the feedback system looks like an issue tracker, so imho it is preferable over the mailto link. Downside: You need a Google+ account to provide feedback.
Imho the optimal solution would be a general feedback page that all clients can link to (as agreed some time ago), still we did not receive a link to such a page.

**Comment by chseifert** [comment]
The general feedback page is likely not going to happen. Thus I would stick with the email link as we have it now because: you don't need a google account to send the mail and the mail is read (it is sent to several people in the project). The vis dashboard then should do the same for general feedback (or provide no own feedback possibility at all). Or we simply use the built-in feedback mechanism from the webstore - no login, but just a installed version required. Pro: people are used to it, and the interface gets cleaner. Cons: Will probably get less feedback - but I don't expect much, anyway.

<img width="1388" alt="screen shot 2015-11-09 at 16 45 15" src="https://cloud.githubusercontent.com/assets/4638470/11038035/48f37fe8-8701-11e5-97b4-a6277d8991fe.png">

**Comment by schloett** [comment]
Ok, then the mailto link will stay as is.

Side remark: Ratings in the webstore also require to be logged in, the feedback link mentioned before simply points to the next tab "support"
