### ISSUE TITLE
Query Crumbs vanish and reappear

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/chrome-extension#49]
The query crumbs visualization vanishes sometimes, unfortunately not reproducible. Currently I don't see them when navigating through a web page, they reappear when I click on the EEXCESS icon to display the results and disappear when I click somewhere in the result set. And then they disappear again. I could not find out which event actually makes them reappear.

**Comment by schloett** [comment]
It seems to be a problem of the asynchronous chrome storage access and therefore concurrent read/write operations. Should be fixed in version 1.2.1 (currently under deployment to the webstore). When this version is available, could you please check again and indicate the status here?

**Comment by chseifert** [comment]
works :)
