### ISSUE TITLE
Update status bar to dynamically update to page content

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/chrome-extension#5]
Extent the status bar such that it shows the detected keywords for the currently visible page content. 
Requires: 
- function to retrieve current viewport and keywords within  (see issue #6)
- function to show keywords in status bar
- allow the user to adapt the keywords (add new words from page, delete keyword, manual entry) 
- allow to search based on the keywords

**Comment by schloett** [comment]
keywords can be set in the search bar by providing contextKeywords as defined in the EEXCESS query profile. Users can: (de-)activate keywords, delete keywords, add new keywords manually and change the main topic via drag 'n' drop (can also be edited manually). Whenever a change occurs, a new query will be triggered.
Functionality for adding keywords from the page is still missing, created a new issue #37 for this.
