### ISSUE TITLE
[UI] First time users should get a better notification that results have been arrived

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/chrome-extension#52]
Currently first time users often do not recognise that new results have arrived. So until the user clicks on the results the first time, the plugin should grab the attention of the user in more intense manner (e.g. a red cat hopping through the bar saying "Click here, click here"; more realistic a red blinking number of results with a larger screen size or a blinking EEXCESS logo etc.)

**Comment by chseifert** [comment]
This request has been upvoted by 2 other persons explicitly at the plenary meeting.
Ideas:
a) pop-up (kind of a help bubble)
b) blinking (attracts attention)
I like a) more (first-time users integrated tutorial concept).

Would be nice to have before sending the questionnaire

**Comment by schloett** [comment]
Fixed in https://github.com/EEXCESS/chrome-extension/commit/f922b7991970fee9279a8fe31204f92ae7b97f22, using a)
