### ISSUE TITLE
Error occurs often when visiting some pages

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/chrome-extension#54]
On some Wiki pages if often do not receive results. Instead an "Error" is shown.

One example is: https://en.wikipedia.org/wiki/Roman_aqueduct (e.g. Paragraph Romes Aqueducts). 

Also, the behaviour of the recommender becomes quite unpredictable. Could it be that the recommender hits already a limit?

**Comment by mgrani** [comment]
it might be also related to the privacy level. increasing it gives sometimes really unrelated results :) My privacy settings have been medium. It seems to correlate with longer paragraphs/longer lists of entities.

**Comment by mgrani** [comment]
Just chekced it: Privacy Proxy throws a 500 error.

**Comment by schloett** [comment]
just to be sure: the errors occur also on privacy level "low"? (In that case, obfuscation is turned off)

**Comment by mgrani** [comment]
no, the error did not occur now. We should rename low to None and medium to low. so the semantic is clear.

**Comment by ThomasCerq** [comment]
It was a problem related to PEAS. It came from the fact that it's sometimes impossible to generate fake queries that do not have keywords in common. I fixed it but relaxing this condition when it's not possible to achieve it. It works fine when the query generated from the paragraph Michael mentioned. 
Can someone check out if it works as expected, and close the issue if it does?

**Comment by schloett** [comment]
In order to know which steps I need to carry out to update to the new version: The changes have been applied to PEAS, so a updating the code via bower should do the job?

**Comment by ThomasCerq** [comment]
Yes, bower update should do.

**Comment by schloett** [comment]
Seems fine now. Updated extension is under deployment (v1.4.1).
