### ISSUE TITLE
blacklist provider sites per default

### ISSUE THREAD

**Issue by schloett** [EEXCESS/chrome-extension#55]
add to blacklist upon installation
Update blacklists of current installations via onUpdated:
- check if already in blacklist
- check if in whitelist

**Comment by chseifert** [comment]
I would argue against that for the following reasons:
1.  Exploration: When data providers are not blacklisted, users can move from a "near" match, via the provider side (and that meta data/description) to a better match. Would support a "something like this" notion.
2. Consistency: It might not be clear that EEXCESS is working on some generall/cultural web pages and on some not (the latter ones happen to be the data provider portal page). 

In any case, each page can be blacklisted manually (thus, the non-data-provider case can be manually achieved). One might think of showing a notification for the ability to blacklist. Or think of a tutorial/help page mentioning this.

**Comment by schloett** [comment]
On the help page, it is already mentioned.
![blacklist](https://cloud.githubusercontent.com/assets/4618499/11565017/6937d162-99dc-11e5-9339-198c6d90c684.PNG)

**Comment by chseifert** [comment]
Then, I consider this done :)
