### ISSUE TITLE
resize only after dragging not usable for endusers

### ISSUE THREAD

**Issue by schloett** [EEXCESS/chrome-extension#8]
If I (as an enduser) would not know about the workaround, I would probably never discover it. Maybe the workaround described at the last comment on [http://bugs.jqueryui.com/ticket/3628](http://bugs.jqueryui.com/ticket/3628) could be applied here as well?

**Comment by schloett** [comment]
if the bug is due to the combination of draggable and resizable, I would sacrifice the draggability.

**Comment by chseifert** [comment]
Agree on sacrificing draggability. would not be the full functionality, but it would greatly increase usability.

**Comment by LadyBytes** [comment]
Removing draggable() doesn't solve the problem. I'm still on it though.
